Repository giselle-ferreira/bookshelf_v1, pull requests merged in 2022-01, with the labels that each got.

#57 Melhoria de divisores
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
Labels: experiência

#68 Adição da logo nos cards do feed
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.ts
Labels: bug

#74 Erros de Português
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-compartilhado/app-dialogos/app-dialogos.component.html
  src/app/app-login/app-login.component.html
  src/app/app-login/app-login.component.ts
  src/app/cdd/classes/classes.component.html
  src/assets/dashboard.json
  src/assets/direito.json
Labels: documentation, experiência

#80 Rotina de limpar campos - Login e Cadastro
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/app-login/app-login.component.ts
Labels: bug

#97 Pagina Especial Mes
  src/app/app-compartilhado/app-compartilhado.module.ts
  src/app/app-compartilhado/app-pipes/pipe-traducao.pipe.spec.ts
  src/app/app-compartilhado/app-pipes/pipe-traducao.pipe.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/especial-mes/especial-mes.component.html
  src/app/especial-mes/especial-mes.component.scss
  src/app/especial-mes/especial-mes.component.spec.ts
  src/app/especial-mes/especial-mes.component.ts
  src/app/modelosInterface/especialMes.ts
  src/app/servicosInterface/especial-mes.service.ts
  src/assets/especialMes.json
  src/assets/menuNavegador.json
Labels: implementação

#98 Criação da Página Not-Found
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/not-found/not-found.component.html
  src/app/not-found/not-found.component.scss
  src/app/not-found/not-found.component.spec.ts
  src/app/not-found/not-found.component.ts
  src/assets/imagens/erro404.svg
Labels: experiência

#100 fechamento do diálogo após validação do login
  src/app/app-login/app-login.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
Labels: bug

#102 Melhoria na Toolbar
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
Labels: experiência

#114 Adição de campo de URL pra foto
  src/app/app-cadastro/app-cadastro.component.html
  src/app/app-cadastro/app-cadastro.component.scss
  src/app/app-cadastro/app-cadastro.component.ts
  src/app/navegacao/navegacao.component.html
  src/app/navegacao/navegacao.component.scss
  src/app/servicosInterface/autenticacao-firebase.service.ts
Labels: implementação

#117 Link na logo
  src/app/navegacao/navegacao.component.html
Labels: bug, experiência
